### ISSUE TITLE
Admin footer menu

### ISSUE THREAD

**Issue by JobDoesburg** [KiOui/TOSTI#13]
I think it would be a good design choice to have all front-end admin actions in a special admin menu in the footer (see the mock designs).

This means:

- At the home page:
    - The start / join shift buttons
- At the shift overview page
    - A button to join baking the shift
- At the shift admin
    - A button to switch the allow/disallow order status
    - A button to extend the shift end date with 10 minutes
    - A button to increase the shift capacity (if almost reached)
    - A button to place an order yourself
    - Maybe more....?

**Comment by KiOui** [comment]
Should we really do start/join shift buttons on the home page? The way they are right now are more nice I think.
