### ISSUE TITLE
OpenID name encoding

### ISSUE THREAD

**Issue by JobDoesburg** [KiOui/TOSTI#130]
Sébastiaans name is not properly encoded

**Comment by KiOui** [comment]
It seems to be that the character encoding we are receiving from the OpenID server is already not correct. It should be in UTF-8, which it is but the OpenID server is not encoding the characters correctly. An example, the OpenID server sends us these `%C3%83%C2%A9` characters (which translated to the weird Ã©) but the é should actually be encoded as `%C3%A9`. There is thus nothing we can do about this other then C&CZ updating their OpenID server to result the bug (which I guess is not going to happen any time soon).

Some more information can be found [here](http://mysql.rjweb.org/doc.php/charcoll).

**Comment by JobDoesburg** [comment]
[https://www.i18nqa.com/debug/utf8-debug.html](https://www.i18nqa.com/debug/utf8-debug.html) explains how to fix it

**Comment by KiOui** [comment]
I think we can close this as CNCZ will be removing OpenID
