### ISSUE TITLE
Improve API Documentation

### ISSUE THREAD

**Issue by KiOui** [KiOui/TOSTI#138]

**Comment by JobDoesburg** [comment]
- [ ] Automatically create and set client id for Swagger OAuth in `website/tosti/templates/tosti/swagger.html:41`
- [ ] Change and fix API descriptions. We can use CustomAutoSchema for this. Right now, some descriptions in the schema are faulty.
- [ ]

**Comment by JobDoesburg** [comment]
Closed in #252
