### ISSUE TITLE
Display link to Marietje-zuid on venue cards

### ISSUE THREAD

**Issue by JobDoesburg** [KiOui/TOSTI#254]

**Comment by wkuijltjes** [comment]
Perhaps even live-stream the Marietje display (e.g. https://marietje-zuid.nl/beeldscherm/ etc.) to show what song is being played

**Comment by JobDoesburg** [comment]
> Perhaps even live-stream the Marietje display (e.g. https://marietje-zuid.nl/beeldscherm/ etc.) to show what song is being played

If you would make the display available without authentication, we could implement it

**Comment by Keessaus** [comment]
Without authentication seems like a no. Maybe with some kind of authentication token or with some IP/subnet restrictions.

**Comment by JobDoesburg** [comment]
> Without authentication seems like a no.

Why exactly? Viewing the screen wouldn't be problematic right? It isn't showing anything secret

> Maybe with some kind of authentication token or with some IP/subnet restrictions.

I would just want to implement it with an iframe. You can put it behind some firewall, so then it would break for users not on eduroam.

**Comment by DeD1rk** [comment]
Or perhaps tell zuidcie to retire marietje and setup spotify...

**Comment by Keessaus** [comment]
Gelukkig nieuwjaar! Op een goede samenwerking tussen Marietje en Tosti :confetti_ball:

**Comment by KiOui** [comment]
As already explained above, we will need some kind of way to access what Marietje is currently playing. I suggest not implementing any form of controls (play/pause/etc.) as these permissions need to be handled by Marietje itself.

@Keessaus could you provide us with a way to access the currently playing song and artist information via a token/OAuth/something else? We can then show this information to logged-in users if that is okay with you.

**Comment by KiOui** [comment]
Once [this PR on Marietje](https://gitlab.science.ru.nl/technicie/MarietjeDjango/-/merge_requests/62) is accepted and merged, we can use an endpoint on Marietje with [Resource Owner Password Credentials  in OAuth 2.0](https://www.rfc-editor.org/rfc/rfc6749#section-4.3).
