### ISSUE TITLE
Move finished tosti orders out of sight

### ISSUE THREAD

**Issue by wkuijltjes** [KiOui/TOSTI#258]
If ordered tosti's are done, it would be nice if these could move down in the list, perhaps enter a second list below the 'processing' list such that the tosti's that still have to be made remain at the top of the screen to prevent unncessary scrolling for the tosticie members running the shift.

**Comment by JobDoesburg** [comment]
We can probably create to tabs for this

**Comment by JobDoesburg** [comment]
@KiOui as this is heavy frontend/Vue related and no backend, can I assign this to you?

**Comment by KiOui** [comment]
> @KiOui as this is heavy frontend/Vue related and no backend, can I assign this to you?

Yes
