### ISSUE TITLE
Permission model

### ISSUE THREAD

**Issue by JobDoesburg** [KiOui/TOSTI#29]
Instead of using the `is_staff` flag to determine whether someone is a baker, and `is_superuser` to check whether they can see the full admin, there should be a better permission model, with groups per venue and venue/shift specific permissions:

- Only assignees to a shift should be able to access a shift
- Users can only assign themselves to a shift during that shift
- Only super users should be able to change a shift after it is finished
- Only people assigned to a venue can start a shift at that venue
- Maybe more permissions should exist...

**Comment by JobDoesburg** [comment]
We could use `django-guardian` for this. I checked it out and it does work, although it is not really user-friendly and might be too powerful for our setup. What do you think Lars?

This would be how the UI would look:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/7915741/85933067-edc56100-b8d2-11ea-90cc-62d14afedd16.png">
<img width="1737" alt="image" src="https://user-images.githubusercontent.com/7915741/85933072-03d32180-b8d3-11ea-94e6-0c5ea987029b.png">
<img width="1737" alt="image" src="https://user-images.githubusercontent.com/7915741/85933078-0fbee380-b8d3-11ea-92e1-b4a463e5940c.png">

**Comment by JobDoesburg** [comment]
We could also build something more personalized to our own needs

**Comment by JobDoesburg** [comment]
The powerful thing would be that with this, we could also use the same permission model to only allow assigned bakers to review orders and such, so it is really powerful indeed

**Comment by KiOui** [comment]
I think django guardian suits our needs (we also used it in Equestria)
