### ISSUE TITLE
Improve time before a consecutive log-in is required

### ISSUE THREAD

**Issue by wkuijltjes** [KiOui/TOSTI#298]
It seems that I have to re-log-in basically every day on the same device, which is quite annoying.

**Comment by JobDoesburg** [comment]
This is out of our hands, we need to respect university SSO session expiration (I'm not sure what their policies are exactly, but every day sounds plausible). 

It is possible that, additionally, you also need to re-login after we release a new version - which in the past few days we almost did twice a day 🙂, so it might become less of a problem when the system is more stable and we will release less often.
