### ISSUE TITLE
Add cleaning schedule to schedule

### ISSUE THREAD

**Issue by dhoekstra2000** [KiOui/TOSTI#300]
Every day another association is responsible for cleaning the canteens, unless there is an activity. It would be nice if the cleaning schedule for each venue could be added to the schedule, such that there is one place where associations & Olympus can look to see who is/was responsible for cleaning the canteen on a given day.

**Comment by JobDoesburg** [comment]
I hate to use the word, but for me it feels like a little bit of feature creep to implement this, as the cleaning schedule is just a mapping of weekdays to associations, right? If people remember to have a look at tosti to see who is on the schedule, probably they will already know that they are responsible.

**Comment by dhoekstra2000** [comment]
Fair, I closed the issue.
