### ISSUE TITLE
Change thaliedje queue template, only show 10 most recent requests and modal for requesting songs

### ISSUE THREAD

**Issue by JobDoesburg** [KiOui/TOSTI#306]
> @KiOui you probably know how to make `website/thaliedje/templates/thaliedje/queue.html` nicer and just hide the column if the API doesn't provide the data, instead of changing it in the template, right?
> 
> Also, it would be nice to only display the 10 most recent requests, and display a button to launch a modal showing the other requested songs

Good idea! Will do

_Originally posted by @KiOui in https://github.com/KiOui/TOSTI/issues/297#issuecomment-1178962532_

**Comment by KiOui** [comment]
Is this still relevant?

**Comment by JobDoesburg** [comment]
Yes, kinda, with the new queue endpoint from spotipy
