### ISSUE TITLE
Volume limiting during daytime

### ISSUE THREAD

**Issue by dhoekstra2000** [KiOui/TOSTI#339]
Currently, the volume of the music in the North canteen can be quite loud during the daytime. Not everyone can control the volume. It would be nice if the volume is reset to say 60% every day such that people are not bothered by loud music. This limit could be released after 4 pm.

**Comment by JobDoesburg** [comment]
I personally would call this feature creep as it makes the system very complex and thus harder to maintain, and it can easily be solved by just adjusting the max volume of the amplifier or instructing people with volume permissions to not go to the max volume.

If you want to go louder during an event, people should just change the amplifier in my opinion.

If there's an additional use case I'm missing please let me know.

Note that I am planning on changing the permission model for canteen reservations itself, meaning that during a reservation, there will be a QR code to scan / URL to visit that will give people access to thaliedje during the reservation

**Comment by JobDoesburg** [comment]
> Note that I am planning on changing the permission model for canteen reservations itself, meaning that during a reservation, there will be a QR code to scan / URL to visit that will give people access to thaliedje during the reservation 

This has just been released
