### ISSUE TITLE
Borrelreservations not showing up in the agenda

### ISSUE THREAD

**Issue by TartarusTim** [KiOui/TOSTI#342]
Enkele borrelreserveringen komen niet in de agenda voor. Voor zover ik weet is dit alleen bij borrelreserveringen waarbij geen kantine is gereserveerd, bij de borrelreservering zelf. Dus als mensen een venue reservering doen en vervolgens geen locatie aangeven in de borrelreservering. Voorbeeld Desda borrel van 14-09

**Comment by KiOui** [comment]
This is intended behavior, we can do two things:

- Also add borrelreservations to the calendar
- Add a separate borrelreservations calendar

Note that the calendar export at [https://tosti.science.ru.nl/borrel/borrel-reservations.ics](https://tosti.science.ru.nl/borrel/borrel-reservations.ics) can be added to your Google agenda to show all borrel reservations in your own calendar.
