### ISSUE TITLE
UX oriented buttons and texts

### ISSUE THREAD

**Issue by JobDoesburg** [KiOui/TOSTI#35]
Some buttons and texts right now have a big focus on the underlying model / code:

- "Back to order screen" 
- "Payment needed"
- "Click to go to status page"
- "Order items"

For UX purposes, it would be better to replace those to things such as 

- "Back to overview"
- "Not paid"
- "Check your order"
- "Place order"

These are just examples and might be outdated, it is however important to keep an eye on these things.

**Comment by KiOui** [comment]
We should look at this issue as one of the last ones before releasing.
