### ISSUE TITLE
Erase queue when playlist or album is queued in Thaliedje

### ISSUE THREAD

**Issue by KiOui** [KiOui/TOSTI#359]
The current queue should be erased when a user queues a playlist or album. Now one of the songs of the playlist or album plays and then the queue resumes.

**Comment by Gulianrdgd** [comment]
Would the expected result be that all requests in the database are dropped or that the page shows an empty request queue?

**Comment by KiOui** [comment]
I think this goes hand-in-hand with the implementation of a live queue (instead of the one we have right now, which does not represent the real Spotify queue). When playing a playlist or album, we should erase all the currently queued music from the Spotify client (and with a live queue this is then automatically transferred to our view).

**Comment by Gulianrdgd** [comment]
I looked around the Spotify API documentation and I don't see a way to clear the Spotify queue using the API

**Comment by KiOui** [comment]
F

**Comment by JobDoesburg** [comment]
Wee have a different queue system right now
