### ISSUE TITLE
Order numbers are different due to soda/snack sales

### ISSUE THREAD

**Issue by wkuijltjes** [KiOui/TOSTI#363]
At the moment the numbers that the people that order their tostis see is not the same as the number shown in the admin screen if there have been soda or snack sales before they have ordered. Figuring out a way to ensure these numbers stay the same (perhaps by just giving soda/snack sales roman numerals or no numbers at all) might be convenient, i.e. when people come to pay and communicate their order number to make sure the correct order is set to "paid".

**Comment by DeD1rk** [comment]
With the new tabs, order numbers are not at all related any more. But since we have last names just now as admin, I think it's best to just do it by name only anyway.

**Comment by DeD1rk** [comment]
At least imo the index in 'to be processed' is a useful estimation of waiting time, whereas replacing that with non-sequential numbers that correspond to what the buyers see would be chaotic for us
