### ISSUE TITLE
Shift (django) admin is awfully slow

### ISSUE THREAD

**Issue by DeD1rk** [KiOui/TOSTI#379]
This makes it really a pain to modify details about a shift, such as deleting orders, changing hamcheese to cheese, or adding a few orders manually. It's also not possible to handle payments while waiting for the admin to load, because all changes will be reset to thier state at the time of laoding when the admin is saved.

So to solve this, the admin needs to be optimized a bit. I propose making the user and association in the order inlines readonly (autocomplete would help too but that's tricky and still slower), so they don't render all users in a dropdown, and instead adding a separate view/button to manually add orders.
Ideally, this (force-adding and perhaps removing orders) could even be done from the normal shift admin vue side, or with a separate view thats easily reachable from a button on the vue shift admin.

**Comment by KiOui** [comment]
+1
