### ISSUE TITLE
Fix players API giving 500

### ISSUE THREAD

**Issue by DeD1rk** [KiOui/TOSTI#426]
For some reason https://tosti.science.ru.nl/api/v1/thaliedje/players/ gives a 500.

That's not good.

**Comment by DeD1rk** [comment]
<img width="686" alt="afbeelding" src="https://user-images.githubusercontent.com/41264528/214356680-3e1b8bde-717c-4733-b4c0-25993f5ac473.png">

Seems like the serializer doesn't catch the overriden implementations because it gets a Player instead of SpotfiyPlayer/MarietjePlayer from the queryset

**Comment by JobDoesburg** [comment]
Has just been resolved
