### ISSUE TITLE
Icon indicating the usage of a paper list

### ISSUE THREAD

**Issue by dhoekstra2000** [KiOui/TOSTI#444]
Currently, in one of the canteens, paper lists are still being used. During the GM of Olympus it was requested to investigate if it is possible to show an icon at those shifts to indicate that both paper and digital lists are being used. The rationale behind this is that it could be misleading for customers with regard to the waiting time.

Is something like this possible?

**Comment by KiOui** [comment]
I think it is in general not a very good idea to use both a paper list and an online list. If people need to order a tosti without being able to login a baker could always add the tosti's manually to the list by either using the barcode scanner and searching for "tosti" or using the backend admin interface.

**Comment by JobDoesburg** [comment]
I agree with Lars, it feels weird to implement a feature in the website saying that we're not using features on the website
