### ISSUE TITLE
Start shift view should suggest datetime.now() as start time instead of default values

### ISSUE THREAD

**Issue by JobDoesburg** [KiOui/TOSTI#46]
Start shift view should suggest datetime.now() as start time instead of default values.

Currently, when you hit the 'start shift' button, the time of the shift is overwritten to default values. This is not desirable when creating a shift via the 'start shift' button since you want to start a shift right at that moment. 

Maybe the form should also include a checkbox whether orders are immediately allowed or not

**Comment by KiOui** [comment]
But is this desirable? It might be better to just start all shifts at the same time every day.

**Comment by JobDoesburg** [comment]
But it is weird if you say “start shift” and it doesn’t start

**Comment by KiOui** [comment]
Okay, good point.
