### ISSUE TITLE
Zorgen dat mensen daadwerkelijk genoeg flesjes bestellen

### ISSUE THREAD

**Issue by mieraaaaa** [KiOui/TOSTI#465]
Kunnen jullie ervoor zorgen dat je perse een veelvoud van 12 (of misschien 6) in moet vullen bij de biersoorten? Dan kunnen mensen niet 1 biertje bestellen wanneer ze eigenlijk 1 kratje willen

**Comment by KiOui** [comment]
Hey Miera, thanks for the issue. Implementing the feature you are describing is more difficult than the profit we gain from it (e.g. we need to make an exception to a certain amount of products connected to a specific category). I would therefor recommend just checking this when accepting borrel reservations, and contacting the party when the Voorraadcie thinks they have made a mistake.
