### ISSUE TITLE
Remove 'items in cart' is user cannot order

### ISSUE THREAD

**Issue by JobDoesburg** [KiOui/TOSTI#47]
When you have reached the max number of orders you can place (there is nothing you can order anymore), there will remain an empty 'items in cart' section on the order page. This should only be visible when a user can indeed order (or even only when a user has ordered items).

I propose to either 
- don't display the items in cart section if a user cannot order anymore
- or simpler, hide the section if there are no items in the cart at all

**Comment by KiOui** [comment]
If you agree with the interface of #64 we can also close this issue.
