### ISSUE TITLE
Bierkoelkast module

### ISSUE THREAD

**Issue by KiOui** [KiOui/TOSTI#483]
Okay, situation: You are standing in front of the beer fridge, you feel inside your left pocket BUT! No money! Wouldn't it be nice to be able to drink on "factuur". You just enter the amount of beer you take from the fridge in TOSTI and then you get an invoice afterwards, super easy!

**Comment by KiOui** [comment]
@JobDoesburg @dhoekstra2000 would like to have your opinion on this as well

**Comment by JobDoesburg** [comment]
Implementation is easy! It's basically a tikkie URL on the website

**Comment by JobDoesburg** [comment]
So the boards opinion is most important
