### ISSUE TITLE
Submit borrelform before end time

### ISSUE THREAD

**Issue by dhoekstra2000** [KiOui/TOSTI#489]
Currently, it seems you are unable to submit the borrelform between the end time of the barrel.

However, sometimes, borrels end before the end time so it would be nice if the borrelform could be submitted any moment after the start time.

**Comment by JobDoesburg** [comment]
This should be possible as per  https://github.com/KiOui/TOSTI/blob/master/website/borrel/models.py#L141-L144

We only check if the start time has passed. Are you sure that it is after the start time? Because I cannot reproduce this behavior.
