### ISSUE TITLE
Blacklist for users

### ISSUE THREAD

**Issue by KiOui** [KiOui/TOSTI#52]
Staff users must be able to blacklist other users if they don't pay or pick up their orders.

**Comment by KiOui** [comment]
Maybe add a banner if a user is not able to order for a specific venue, otherwise this is already fixed in #87

**Comment by JobDoesburg** [comment]
Blacklist == remove a user from the 'can_order_in` group

**Comment by JobDoesburg** [comment]
Maybe we should automatically create Groups for all custom permissions and all objects in that model.

**Comment by JobDoesburg** [comment]
This is already realized by #87
