### ISSUE TITLE
Greylist (Softer version of Blacklist)

### ISSUE THREAD

**Issue by mark-boute** [KiOui/TOSTI#527]
Some students tend to be very late with picking up their tosti's, without deprioritizing their order. This is very annoying for the Tosticie. To help them a little a list of these students could come in useful, those who are in this list get deprioritized automatically.

**Comment by KiOui** [comment]
I think it is better to implement #528. I think it's not fair to always place these orders at the bottom of the list at some point.

**Comment by JobDoesburg** [comment]
RT lars, grey list sounds pretty feature creep to me
